### PR TITLE
feat: integrate vue-docgen-api in preview

### PR DESCRIPTION
**Pull request by elevatebart**
Using this new integration we can now leverage docgen on component pages.
I was thinking of making an extra component on the right side (collapsible) that would display all this info and allow to interract with the previews.

It has been my experience that people love to interact and modify preview examples.

### CODE REVIEW

**Review by znck — APPROVED** [review]

**Comment by znck** [comment]
> extra component on the right side
That's a nice idea, go ahead.

> (collapsible)
We should make left-side collapsible too.

**Comment by elevatebart** [comment]
Here is a screenshot of the status today:

Screen Shot 2020-11-24 at 2 26 59 PM

- Added the two collapse buttons (no animation, no design)
- Started rendering the documentation on the right panel

**Comment by znck** [comment]
LGTM.

**Comment by elevatebart** [comment]
I will finish rendering the docs this morning. Then I will merge.

**Comment by elevatebart** [comment]
I have not gotten `.__docgen__` urls to refresh using HMR. I will try to do this in a next PR.

**Pull request merged**
